#!/usr/bin/env python3
"""Generate Oxford-styled .docx for Article Zero interview."""

import re
from docx import Document
from docx.shared import Pt, Mm, Inches, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.enum.section import WD_ORIENT
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml
import copy

# ── Palette ──
OXFORD_BLUE = RGBColor(0x00, 0x21, 0x47)
GOLD = RGBColor(0x88, 0x6D, 0x35)
GOLD_LIGHT = RGBColor(0xC9, 0xA9, 0x61)
WARM_BG = "F7F5F1"
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
DARK_TEXT = RGBColor(0x1A, 0x1A, 0x1A)
MUTED = RGBColor(0x55, 0x55, 0x55)
RULE_GREY = RGBColor(0xD4, 0xCF, 0xC7)

# ── Fonts ──
DISPLAY_FONT = "Garamond"
BODY_FONT = "Garamond"
SANS_FONT = "Gill Sans"
FALLBACK_SERIF = "Georgia"

# ── Content ──
METHOD_NOTE = (
    "Method note: The following primary responses were generated by jdd-kami, "
    "a bounded drafting system developed with Tenzin Yangtso and described publicly "
    "at gh#642998ce.\n\n"
    "The system was run against a fixed local research corpus at gh#0a74e2d5 "
    "and hf#04ac740. After each answer, Audrey Tang either endorses, qualifies, "
    "or corrects the draft."
)

# Parse the markdown content
with open("article-zero.md", "r") as f:
    raw = f.read()

# Strip front matter
raw = re.sub(r"^---.*?---\s*", "", raw, flags=re.DOTALL)
# Strip the aside block (we handle method note separately)
raw = re.sub(r"<aside.*?</aside>\s*", "", raw, flags=re.DOTALL)


def parse_questions(text):
    """Parse the Q&A blocks from the markdown."""
    questions = []
    # Split on h4 tags
    parts = re.split(r'<h4 id="q(\d+)">', text)
    # parts[0] is any content before first question
    for i in range(1, len(parts), 2):
        q_num = parts[i]
        block = parts[i + 1] if i + 1 < len(parts) else ""
        # Extract question text from the h4 closing
        q_match = re.match(r'<a href="#q\d+">Q\d+\.</a>\s*(.*?)</h4>\s*(.*)', block, re.DOTALL)
        if q_match:
            q_text = q_match.group(1).strip()
            body = q_match.group(2).strip()
        else:
            q_text = ""
            body = block

        # Split body into responses by **speaker:** pattern and --- dividers
        body = re.sub(r"\n---\s*$", "", body.strip())

        # Split into speaker responses
        responses = []
        # Prepend \n\n so the first **speaker:** also matches the split pattern
        body_prefixed = "\n\n" + body
        speaker_splits = re.split(r"\n\n\*\*(.*?)\*\*\s*", body_prefixed)
        # speaker_splits[0] is empty, then alternating speaker/content
        for j in range(1, len(speaker_splits), 2):
            speaker = speaker_splits[j].rstrip(":")
            content = speaker_splits[j + 1].strip() if j + 1 < len(speaker_splits) else ""
            responses.append((speaker, content))

        questions.append({
            "num": int(q_num),
            "question": q_text,
            "responses": responses,
        })
    return questions


questions = parse_questions(raw)

# ── Build document ──
doc = Document()

# ── Page setup ──
section = doc.sections[0]
section.page_width = Mm(210)
section.page_height = Mm(297)
section.top_margin = Mm(25)
section.bottom_margin = Mm(25)
section.left_margin = Mm(25)
section.right_margin = Mm(25)
section.header_distance = Mm(10)
section.footer_distance = Mm(10)


def set_font(run, name=BODY_FONT, size=Pt(11), color=DARK_TEXT, bold=False, italic=False):
    run.font.name = name
    run.font.size = size
    run.font.color.rgb = color
    run.font.bold = bold
    run.font.italic = italic
    # Set East Asian font fallback
    rPr = run._element.get_or_add_rPr()
    rFonts = rPr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = parse_xml(f'<w:rFonts {nsdecls("w")} w:ascii="{name}" w:hAnsi="{name}"/>')
        rPr.append(rFonts)
    else:
        rFonts.set(qn("w:ascii"), name)
        rFonts.set(qn("w:hAnsi"), name)


def add_shading(paragraph, color_hex):
    """Add background shading to a paragraph."""
    pPr = paragraph._element.get_or_add_pPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:val="clear" w:color="auto" w:fill="{color_hex}"/>')
    pPr.append(shd)


def add_border_left(paragraph, color_hex="002147", size="12", space="8"):
    """Add a left border to a paragraph."""
    pPr = paragraph._element.get_or_add_pPr()
    borders = parse_xml(
        f'<w:pBdr {nsdecls("w")}>'
        f'  <w:left w:val="single" w:sz="{size}" w:space="{space}" w:color="{color_hex}"/>'
        f'</w:pBdr>'
    )
    pPr.append(borders)


def add_border_bottom(paragraph, color_hex="D4CFC7", size="4"):
    """Add a bottom border to a paragraph."""
    pPr = paragraph._element.get_or_add_pPr()
    borders = parse_xml(
        f'<w:pBdr {nsdecls("w")}>'
        f'  <w:bottom w:val="single" w:sz="{size}" w:space="4" w:color="{color_hex}"/>'
        f'</w:pBdr>'
    )
    pPr.append(borders)


def add_border_top(paragraph, color_hex="D4CFC7", size="4"):
    """Add a top border to a paragraph."""
    pPr = paragraph._element.get_or_add_pPr()
    borders = parse_xml(
        f'<w:pBdr {nsdecls("w")}>'
        f'  <w:top w:val="single" w:sz="{size}" w:space="4" w:color="{color_hex}"/>'
        f'</w:pBdr>'
    )
    pPr.append(borders)


def add_inline_text(paragraph, text, font_name=BODY_FONT, size=Pt(11), color=DARK_TEXT,
                    bold=False, italic=False):
    """Add a run of text with specified formatting."""
    run = paragraph.add_run(text)
    set_font(run, name=font_name, size=size, color=color, bold=bold, italic=italic)
    return run


def parse_inline_markdown(paragraph, text, base_font=BODY_FONT, base_size=Pt(11),
                          base_color=DARK_TEXT):
    """Parse inline markdown (bold, italic) and add runs to paragraph."""
    # Handle **bold** and _italic_ patterns
    parts = re.split(r'(\*\*.*?\*\*|_[^_]+_)', text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            inner = part[2:-2]
            add_inline_text(paragraph, inner, font_name=base_font, size=base_size,
                          color=base_color, bold=True)
        elif part.startswith("_") and part.endswith("_") and len(part) > 2:
            inner = part[1:-1]
            add_inline_text(paragraph, inner, font_name=base_font, size=base_size,
                          color=base_color, italic=True)
        else:
            if part:
                add_inline_text(paragraph, part, font_name=base_font, size=base_size,
                              color=base_color)


# ═══════════════════════════════════════
#  TITLE PAGE / HEADER BLOCK
# ═══════════════════════════════════════

# Oxford blue title block using a table for background color
title_table = doc.add_table(rows=1, cols=1)
title_table.alignment = WD_TABLE_ALIGNMENT.CENTER
cell = title_table.cell(0, 0)

# Set cell shading to Oxford blue
tc = cell._element
tcPr = tc.get_or_add_tcPr()
shd = parse_xml(f'<w:shd {nsdecls("w")} w:val="clear" w:color="auto" w:fill="002147"/>')
tcPr.append(shd)

# Set cell margins
tcMar = parse_xml(
    f'<w:tcMar {nsdecls("w")}>'
    f'  <w:top w:w="600" w:type="dxa"/>'
    f'  <w:left w:w="500" w:type="dxa"/>'
    f'  <w:bottom w:w="600" w:type="dxa"/>'
    f'  <w:right w:w="500" w:type="dxa"/>'
    f'</w:tcMar>'
)
tcPr.append(tcMar)

# Remove table borders
tbl = title_table._element
tblPr = tbl.find(qn("w:tblPr"))
borders = parse_xml(
    f'<w:tblBorders {nsdecls("w")}>'
    f'  <w:top w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
    f'  <w:left w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
    f'  <w:bottom w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
    f'  <w:right w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
    f'  <w:insideH w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
    f'  <w:insideV w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
    f'</w:tblBorders>'
)
tblPr.append(borders)

# Make table full width
tblW = parse_xml(f'<w:tblW {nsdecls("w")} w:w="5000" w:type="pct"/>')
tblPr.append(tblW)

# Title text
p = cell.paragraphs[0]
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
p.space_before = Pt(8)
p.space_after = Pt(4)
run = p.add_run("Interview with Article Zero")
set_font(run, name=DISPLAY_FONT, size=Pt(26), color=WHITE, bold=False)

# Subtitle / institutional line
p2 = cell.add_paragraph()
p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
p2.space_before = Pt(4)
p2.space_after = Pt(2)
run = p2.add_run("6-Pack of Care")
set_font(run, name=SANS_FONT, size=Pt(9), color=RGBColor(0xC9, 0xA9, 0x61), bold=False)

# Gold rule
p3 = cell.add_paragraph()
p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
p3.space_before = Pt(6)
p3.space_after = Pt(6)
run = p3.add_run("━━━━━━━━")
set_font(run, name=SANS_FONT, size=Pt(8), color=GOLD_LIGHT)

# Institution
p4 = cell.add_paragraph()
p4.alignment = WD_ALIGN_PARAGRAPH.CENTER
p4.space_before = Pt(2)
p4.space_after = Pt(4)
run = p4.add_run("Oxford Institute for Ethics in AI  ·  Accelerator Fellowship Programme")
set_font(run, name=SANS_FONT, size=Pt(7.5), color=RGBColor(0xAA, 0xBB, 0xCC))

# ── Spacer ──
spacer = doc.add_paragraph()
spacer.space_before = Pt(6)
spacer.space_after = Pt(6)

# ── Institutional sub-header ──
inst_line = doc.add_paragraph()
inst_line.alignment = WD_ALIGN_PARAGRAPH.CENTER
inst_line.space_before = Pt(0)
inst_line.space_after = Pt(12)
add_border_bottom(inst_line, color_hex="002147", size="4")
run = inst_line.add_run("6-PACK OF CARE  ·  OXFORD INSTITUTE FOR ETHICS IN AI  ·  ACCELERATOR FELLOWSHIP PROGRAMME")
set_font(run, name=SANS_FONT, size=Pt(6), color=OXFORD_BLUE)
run.font.all_caps = True

# ═══════════════════════════════════════
#  METHOD NOTE
# ═══════════════════════════════════════

for i, para_text in enumerate(METHOD_NOTE.split("\n\n")):
    mn = doc.add_paragraph()
    mn.space_before = Pt(2) if i > 0 else Pt(4)
    mn.space_after = Pt(2)
    mn.paragraph_format.line_spacing = Pt(13)
    add_border_left(mn, color_hex="002147", size="12", space="10")
    add_shading(mn, WARM_BG)
    # Left indent for visual padding
    mn.paragraph_format.left_indent = Mm(2)
    mn.paragraph_format.right_indent = Mm(2)
    add_inline_text(mn, para_text, font_name=SANS_FONT, size=Pt(8.5), color=MUTED)

# Spacer after method note
spacer2 = doc.add_paragraph()
spacer2.space_before = Pt(6)
spacer2.space_after = Pt(6)

# ═══════════════════════════════════════
#  QUESTIONS & ANSWERS
# ═══════════════════════════════════════

for qi, q in enumerate(questions):
    # ── Gold ornamental divider (between questions, not before first) ──
    if qi > 0:
        div = doc.add_paragraph()
        div.alignment = WD_ALIGN_PARAGRAPH.CENTER
        div.space_before = Pt(18)
        div.space_after = Pt(18)
        run = div.add_run("◆")
        set_font(run, name=BODY_FONT, size=Pt(7), color=GOLD_LIGHT)

    # ── Question heading ──
    qp = doc.add_paragraph()
    qp.space_before = Pt(6)
    qp.space_after = Pt(10)
    qp.paragraph_format.line_spacing = Pt(16)
    qp.paragraph_format.keep_with_next = True

    # Q number in gold
    run_num = qp.add_run(f"Q{q['num']}.  ")
    set_font(run_num, name=DISPLAY_FONT, size=Pt(12.5), color=GOLD, bold=True)

    # Question text in Oxford blue
    parse_inline_markdown(qp, q["question"], base_font=DISPLAY_FONT, base_size=Pt(12.5),
                         base_color=OXFORD_BLUE)
    # Make all runs in the question bold
    for run in qp.runs:
        if run.font.color.rgb == OXFORD_BLUE:
            run.font.bold = True

    # ── Responses ──
    for ri, (speaker, content) in enumerate(q["responses"]):
        # Speaker label
        sp = doc.add_paragraph()
        sp.space_before = Pt(10) if ri == 0 else Pt(12)
        sp.space_after = Pt(4)
        if ri > 0:
            add_border_top(sp, color_hex="D4CFC7", size="2")
            sp.space_before = Pt(14)

        # Determine if this is Audrey's response and its type
        is_audrey = "Audrey Tang" in speaker
        speaker_display = speaker.replace(" —", " —")  # ensure proper em dash

        if is_audrey:
            # Parse the response type
            if "Endorsement" in speaker and "Correction" in speaker:
                label_color = RGBColor(0x8B, 0x45, 0x13)  # sienna for correction
            elif "Correction" in speaker:
                label_color = RGBColor(0x8B, 0x45, 0x13)
            elif "Qualification" in speaker:
                label_color = RGBColor(0x5B, 0x4A, 0x2A)
            else:
                label_color = OXFORD_BLUE
        else:
            label_color = OXFORD_BLUE

        run_speaker = sp.add_run(speaker_display)
        set_font(run_speaker, name=SANS_FONT, size=Pt(8), color=label_color, bold=True)
        run_speaker.font.all_caps = True

        # Content paragraphs
        paragraphs = content.split("\n\n")
        for pi, para in enumerate(paragraphs):
            para = para.strip()
            if not para:
                continue

            pp = doc.add_paragraph()
            pp.space_before = Pt(3)
            pp.space_after = Pt(3)
            pp.paragraph_format.line_spacing_rule = WD_LINE_SPACING.MULTIPLE
            pp.paragraph_format.line_spacing = 1.42

            # First paragraph of jdd-kami gets a slight left indent (book style)
            if pi == 0 and not is_audrey:
                pass  # no indent on first para
            elif not is_audrey:
                pp.paragraph_format.first_line_indent = Mm(5)

            # Audrey's responses get left border accent
            if is_audrey:
                add_border_left(pp, color_hex="886D35", size="8", space="10")

            parse_inline_markdown(pp, para, base_font=BODY_FONT, base_size=Pt(10.8),
                                base_color=DARK_TEXT)


# ═══════════════════════════════════════
#  FOOTER IMPRINT
# ═══════════════════════════════════════

footer_spacer = doc.add_paragraph()
footer_spacer.space_before = Pt(24)
footer_spacer.space_after = Pt(0)

footer_p = doc.add_paragraph()
footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
footer_p.space_before = Pt(8)
footer_p.space_after = Pt(0)
add_border_top(footer_p, color_hex="002147", size="4")
run = footer_p.add_run(
    "© 2025 AUDREY TANG & CAROLINE GREEN  ·  OXFORD INSTITUTE FOR ETHICS IN AI  ·  UNIVERSITY OF OXFORD"
)
set_font(run, name=SANS_FONT, size=Pt(6), color=OXFORD_BLUE)
run.font.all_caps = True

# ═══════════════════════════════════════
#  HEADERS & FOOTERS
# ═══════════════════════════════════════

# Running header
header = section.header
header.is_linked_to_previous = False
hp = header.paragraphs[0]
hp.alignment = WD_ALIGN_PARAGRAPH.CENTER
hp.space_after = Pt(4)
add_border_bottom(hp, color_hex="C9A961", size="2")
run = hp.add_run("INTERVIEW WITH ARTICLE ZERO")
set_font(run, name=SANS_FONT, size=Pt(6.5), color=GOLD)
run.font.all_caps = True

# Running footer with page number
footer_sec = section.footer
footer_sec.is_linked_to_previous = False
fp = footer_sec.paragraphs[0]
fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
fp.space_before = Pt(6)
add_border_top(fp, color_hex="D4CFC7", size="2")

# Add page number field
run_pre = fp.add_run("— ")
set_font(run_pre, name=DISPLAY_FONT, size=Pt(8.5), color=MUTED)

# Page number field code
fldChar1 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="begin"/>')
run1 = fp.add_run()
run1._element.append(fldChar1)

instrText = parse_xml(f'<w:instrText {nsdecls("w")} xml:space="preserve"> PAGE </w:instrText>')
run2 = fp.add_run()
set_font(run2, name=DISPLAY_FONT, size=Pt(8.5), color=OXFORD_BLUE)
run2._element.append(instrText)

fldChar2 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="end"/>')
run3 = fp.add_run()
run3._element.append(fldChar2)

run_post = fp.add_run(" —")
set_font(run_post, name=DISPLAY_FONT, size=Pt(8.5), color=MUTED)

# ═══════════════════════════════════════
#  SAVE
# ═══════════════════════════════════════

out = "article-zero.docx"
doc.save(out)
print(f"✓ Saved {out}")
